//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/GameInput/GameInpuMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInpuMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInpuMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInpuMap"",
    ""maps"": [
        {
            ""name"": ""MainInputMap"",
            ""id"": ""e8d7113a-db22-43ca-8155-d805a65818cf"",
            ""actions"": [
                {
                    ""name"": ""MovementBinds"",
                    ""type"": ""Value"",
                    ""id"": ""d65c913a-1dce-49a1-b79a-5055e5a45c6b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AnalogMovementBinds"",
                    ""type"": ""Value"",
                    ""id"": ""e67141d0-3233-4eac-a374-dccf61f1beb1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ActionBind1"",
                    ""type"": ""Value"",
                    ""id"": ""9efaf24b-57e4-4f59-b42a-352f79dc7d82"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ActionBind2"",
                    ""type"": ""Value"",
                    ""id"": ""f0c3513c-2141-461f-ac98-acacc854d232"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ActionBind3"",
                    ""type"": ""Value"",
                    ""id"": ""a5b02fda-f4ec-436b-9708-16d8a117ac06"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ActionBind4"",
                    ""type"": ""Value"",
                    ""id"": ""c2a1073a-83ad-43e8-870c-7e7e8f9f0950"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SpaceInput"",
                    ""type"": ""Value"",
                    ""id"": ""478655bf-f784-4a33-a18a-863468a53afb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ShiftInput"",
                    ""type"": ""Value"",
                    ""id"": ""2e26a7d8-341e-4818-bb0d-e68548d81ad0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""EInput"",
                    ""type"": ""Value"",
                    ""id"": ""d5174b52-f613-4464-8ddb-1cc587560e41"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""QInput"",
                    ""type"": ""Value"",
                    ""id"": ""ba84fe81-9157-45db-8c94-27b9d9de5e8c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MenuBinds"",
                    ""type"": ""Button"",
                    ""id"": ""2342f8bb-c516-4094-8f7c-2708df0e5b04"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConfirmBinds"",
                    ""type"": ""Button"",
                    ""id"": ""3052e4b2-7908-4ff0-8e57-8e0fb15eef03"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseAimBind"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5e6c2827-f1cd-4b12-86c1-251a9ee13aa7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""KeyboardMainInputs"",
                    ""id"": ""7ffbeb3f-ceaf-4c75-bda5-27ecb730e8de"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementBinds"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5d6f9b0d-89e1-4e26-94b4-d8f3c543f630"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""96fecae5-9792-4136-908b-bfd6bb14e322"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""102dd3ad-4a3d-4949-9b4a-d664d04b7f6f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a062ee9d-6433-43e2-b8df-6ae1c4cdc85c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""7d689115-ba4c-4399-bfe6-3e8541c86eac"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementBinds"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""122bf104-0918-40e6-9ea9-9939c38a6409"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""088203f4-9fee-4f0e-a43f-1fe992f4e364"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""73ab271f-b309-4513-a73c-e796472330bd"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3cccd07d-a4f4-4e93-b730-d776222b0ceb"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamepadStickInputs"",
                    ""id"": ""3c9c84f3-1fe8-4749-9189-d04265acc531"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementBinds"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f6ed596f-4d42-4c55-aa1e-62e88dc10adf"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c1a72f2c-93b1-4bf2-a567-576f215a8e34"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4c677b5c-a636-453c-9188-3b44e030aefe"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""106435c7-213c-461e-8530-94d799f73eb3"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5325c9a8-b0ca-41bc-aef9-9ba393374934"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionBind1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca2b894a-f018-4a20-8d5e-4574118f7e1b"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94fc62a9-350b-4b37-9106-cd9521aa2b89"",
                    ""path"": ""<Gamepad>/home"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""461a3cdf-f487-495f-9a3b-c982db2df27e"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConfirmBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccd31d70-3184-454c-83cf-b8bee17e20af"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConfirmBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03b675ed-a721-4a9d-b757-7f55a227e5b0"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionBind2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e22bdd1a-9c6f-47a3-9902-7c1d3cc8062b"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionBind3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be6e0117-fe37-4c1a-9ecb-0be642f28420"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionBind4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2a1d2ef-4c1a-4e7b-a6c1-184605642b01"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpaceInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3d96924-8167-4362-beec-2edbb8fe2530"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e70bef9-c4c1-4291-8384-5b5d774d0c26"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2de33001-b80f-47cc-bdc6-2d1b8e40739b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""KeyboardMainInputs"",
                    ""id"": ""bc808c95-2fce-43da-a201-b4834b535057"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovementBinds"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b504f5a0-c74e-4f39-87e4-c6e9341cc5b8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b3ab794b-baaf-4744-a3ea-50162e90dbb0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cc2f43e6-814e-4f7e-a542-8616b77c8eaf"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""569d7ebf-b154-42da-988d-951421593540"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamepadStickInputs"",
                    ""id"": ""15cee3b8-c309-4141-967f-6cb4c9f55643"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovementBinds"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2f55bbaa-8b67-45c3-9186-6c4e0c7275f7"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7de113ea-5bef-46c0-b067-4f5391000ae4"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""514ba154-06bd-438a-80e4-86719e6fbd59"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5ba1bd6a-7212-4538-bbc9-149e93641c16"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""037a8c69-b0e7-42e9-b5dc-bcb5d3759fe9"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovementBinds"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""aac062eb-5890-4137-9f30-ad32a2fd6260"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fa1866d0-4118-4997-b0fd-72704417e0b4"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7d1d2e9c-0750-4c0f-b218-83bc9316013b"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c4a15623-f478-469a-a0a4-f1f60289dd86"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovementBinds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c4089540-c007-438b-a96d-f546faa12348"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseAimBind"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MainInputMap
        m_MainInputMap = asset.FindActionMap("MainInputMap", throwIfNotFound: true);
        m_MainInputMap_MovementBinds = m_MainInputMap.FindAction("MovementBinds", throwIfNotFound: true);
        m_MainInputMap_AnalogMovementBinds = m_MainInputMap.FindAction("AnalogMovementBinds", throwIfNotFound: true);
        m_MainInputMap_ActionBind1 = m_MainInputMap.FindAction("ActionBind1", throwIfNotFound: true);
        m_MainInputMap_ActionBind2 = m_MainInputMap.FindAction("ActionBind2", throwIfNotFound: true);
        m_MainInputMap_ActionBind3 = m_MainInputMap.FindAction("ActionBind3", throwIfNotFound: true);
        m_MainInputMap_ActionBind4 = m_MainInputMap.FindAction("ActionBind4", throwIfNotFound: true);
        m_MainInputMap_SpaceInput = m_MainInputMap.FindAction("SpaceInput", throwIfNotFound: true);
        m_MainInputMap_ShiftInput = m_MainInputMap.FindAction("ShiftInput", throwIfNotFound: true);
        m_MainInputMap_EInput = m_MainInputMap.FindAction("EInput", throwIfNotFound: true);
        m_MainInputMap_QInput = m_MainInputMap.FindAction("QInput", throwIfNotFound: true);
        m_MainInputMap_MenuBinds = m_MainInputMap.FindAction("MenuBinds", throwIfNotFound: true);
        m_MainInputMap_ConfirmBinds = m_MainInputMap.FindAction("ConfirmBinds", throwIfNotFound: true);
        m_MainInputMap_MouseAimBind = m_MainInputMap.FindAction("MouseAimBind", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MainInputMap
    private readonly InputActionMap m_MainInputMap;
    private List<IMainInputMapActions> m_MainInputMapActionsCallbackInterfaces = new List<IMainInputMapActions>();
    private readonly InputAction m_MainInputMap_MovementBinds;
    private readonly InputAction m_MainInputMap_AnalogMovementBinds;
    private readonly InputAction m_MainInputMap_ActionBind1;
    private readonly InputAction m_MainInputMap_ActionBind2;
    private readonly InputAction m_MainInputMap_ActionBind3;
    private readonly InputAction m_MainInputMap_ActionBind4;
    private readonly InputAction m_MainInputMap_SpaceInput;
    private readonly InputAction m_MainInputMap_ShiftInput;
    private readonly InputAction m_MainInputMap_EInput;
    private readonly InputAction m_MainInputMap_QInput;
    private readonly InputAction m_MainInputMap_MenuBinds;
    private readonly InputAction m_MainInputMap_ConfirmBinds;
    private readonly InputAction m_MainInputMap_MouseAimBind;
    public struct MainInputMapActions
    {
        private @GameInpuMap m_Wrapper;
        public MainInputMapActions(@GameInpuMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovementBinds => m_Wrapper.m_MainInputMap_MovementBinds;
        public InputAction @AnalogMovementBinds => m_Wrapper.m_MainInputMap_AnalogMovementBinds;
        public InputAction @ActionBind1 => m_Wrapper.m_MainInputMap_ActionBind1;
        public InputAction @ActionBind2 => m_Wrapper.m_MainInputMap_ActionBind2;
        public InputAction @ActionBind3 => m_Wrapper.m_MainInputMap_ActionBind3;
        public InputAction @ActionBind4 => m_Wrapper.m_MainInputMap_ActionBind4;
        public InputAction @SpaceInput => m_Wrapper.m_MainInputMap_SpaceInput;
        public InputAction @ShiftInput => m_Wrapper.m_MainInputMap_ShiftInput;
        public InputAction @EInput => m_Wrapper.m_MainInputMap_EInput;
        public InputAction @QInput => m_Wrapper.m_MainInputMap_QInput;
        public InputAction @MenuBinds => m_Wrapper.m_MainInputMap_MenuBinds;
        public InputAction @ConfirmBinds => m_Wrapper.m_MainInputMap_ConfirmBinds;
        public InputAction @MouseAimBind => m_Wrapper.m_MainInputMap_MouseAimBind;
        public InputActionMap Get() { return m_Wrapper.m_MainInputMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainInputMapActions set) { return set.Get(); }
        public void AddCallbacks(IMainInputMapActions instance)
        {
            if (instance == null || m_Wrapper.m_MainInputMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainInputMapActionsCallbackInterfaces.Add(instance);
            @MovementBinds.started += instance.OnMovementBinds;
            @MovementBinds.performed += instance.OnMovementBinds;
            @MovementBinds.canceled += instance.OnMovementBinds;
            @AnalogMovementBinds.started += instance.OnAnalogMovementBinds;
            @AnalogMovementBinds.performed += instance.OnAnalogMovementBinds;
            @AnalogMovementBinds.canceled += instance.OnAnalogMovementBinds;
            @ActionBind1.started += instance.OnActionBind1;
            @ActionBind1.performed += instance.OnActionBind1;
            @ActionBind1.canceled += instance.OnActionBind1;
            @ActionBind2.started += instance.OnActionBind2;
            @ActionBind2.performed += instance.OnActionBind2;
            @ActionBind2.canceled += instance.OnActionBind2;
            @ActionBind3.started += instance.OnActionBind3;
            @ActionBind3.performed += instance.OnActionBind3;
            @ActionBind3.canceled += instance.OnActionBind3;
            @ActionBind4.started += instance.OnActionBind4;
            @ActionBind4.performed += instance.OnActionBind4;
            @ActionBind4.canceled += instance.OnActionBind4;
            @SpaceInput.started += instance.OnSpaceInput;
            @SpaceInput.performed += instance.OnSpaceInput;
            @SpaceInput.canceled += instance.OnSpaceInput;
            @ShiftInput.started += instance.OnShiftInput;
            @ShiftInput.performed += instance.OnShiftInput;
            @ShiftInput.canceled += instance.OnShiftInput;
            @EInput.started += instance.OnEInput;
            @EInput.performed += instance.OnEInput;
            @EInput.canceled += instance.OnEInput;
            @QInput.started += instance.OnQInput;
            @QInput.performed += instance.OnQInput;
            @QInput.canceled += instance.OnQInput;
            @MenuBinds.started += instance.OnMenuBinds;
            @MenuBinds.performed += instance.OnMenuBinds;
            @MenuBinds.canceled += instance.OnMenuBinds;
            @ConfirmBinds.started += instance.OnConfirmBinds;
            @ConfirmBinds.performed += instance.OnConfirmBinds;
            @ConfirmBinds.canceled += instance.OnConfirmBinds;
            @MouseAimBind.started += instance.OnMouseAimBind;
            @MouseAimBind.performed += instance.OnMouseAimBind;
            @MouseAimBind.canceled += instance.OnMouseAimBind;
        }

        private void UnregisterCallbacks(IMainInputMapActions instance)
        {
            @MovementBinds.started -= instance.OnMovementBinds;
            @MovementBinds.performed -= instance.OnMovementBinds;
            @MovementBinds.canceled -= instance.OnMovementBinds;
            @AnalogMovementBinds.started -= instance.OnAnalogMovementBinds;
            @AnalogMovementBinds.performed -= instance.OnAnalogMovementBinds;
            @AnalogMovementBinds.canceled -= instance.OnAnalogMovementBinds;
            @ActionBind1.started -= instance.OnActionBind1;
            @ActionBind1.performed -= instance.OnActionBind1;
            @ActionBind1.canceled -= instance.OnActionBind1;
            @ActionBind2.started -= instance.OnActionBind2;
            @ActionBind2.performed -= instance.OnActionBind2;
            @ActionBind2.canceled -= instance.OnActionBind2;
            @ActionBind3.started -= instance.OnActionBind3;
            @ActionBind3.performed -= instance.OnActionBind3;
            @ActionBind3.canceled -= instance.OnActionBind3;
            @ActionBind4.started -= instance.OnActionBind4;
            @ActionBind4.performed -= instance.OnActionBind4;
            @ActionBind4.canceled -= instance.OnActionBind4;
            @SpaceInput.started -= instance.OnSpaceInput;
            @SpaceInput.performed -= instance.OnSpaceInput;
            @SpaceInput.canceled -= instance.OnSpaceInput;
            @ShiftInput.started -= instance.OnShiftInput;
            @ShiftInput.performed -= instance.OnShiftInput;
            @ShiftInput.canceled -= instance.OnShiftInput;
            @EInput.started -= instance.OnEInput;
            @EInput.performed -= instance.OnEInput;
            @EInput.canceled -= instance.OnEInput;
            @QInput.started -= instance.OnQInput;
            @QInput.performed -= instance.OnQInput;
            @QInput.canceled -= instance.OnQInput;
            @MenuBinds.started -= instance.OnMenuBinds;
            @MenuBinds.performed -= instance.OnMenuBinds;
            @MenuBinds.canceled -= instance.OnMenuBinds;
            @ConfirmBinds.started -= instance.OnConfirmBinds;
            @ConfirmBinds.performed -= instance.OnConfirmBinds;
            @ConfirmBinds.canceled -= instance.OnConfirmBinds;
            @MouseAimBind.started -= instance.OnMouseAimBind;
            @MouseAimBind.performed -= instance.OnMouseAimBind;
            @MouseAimBind.canceled -= instance.OnMouseAimBind;
        }

        public void RemoveCallbacks(IMainInputMapActions instance)
        {
            if (m_Wrapper.m_MainInputMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainInputMapActions instance)
        {
            foreach (var item in m_Wrapper.m_MainInputMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainInputMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainInputMapActions @MainInputMap => new MainInputMapActions(this);
    public interface IMainInputMapActions
    {
        void OnMovementBinds(InputAction.CallbackContext context);
        void OnAnalogMovementBinds(InputAction.CallbackContext context);
        void OnActionBind1(InputAction.CallbackContext context);
        void OnActionBind2(InputAction.CallbackContext context);
        void OnActionBind3(InputAction.CallbackContext context);
        void OnActionBind4(InputAction.CallbackContext context);
        void OnSpaceInput(InputAction.CallbackContext context);
        void OnShiftInput(InputAction.CallbackContext context);
        void OnEInput(InputAction.CallbackContext context);
        void OnQInput(InputAction.CallbackContext context);
        void OnMenuBinds(InputAction.CallbackContext context);
        void OnConfirmBinds(InputAction.CallbackContext context);
        void OnMouseAimBind(InputAction.CallbackContext context);
    }
}
